SOURCE_JUGUANG = "juguang"
SOURCE_PGY = "pgy"
SOURCE_XIAOHONGXING_ORDER = "xiaohongxing_order"
SOURCE_NOTE_MAPPING = "note_mapping"
SOURCE_TASK_MAPPING = "task_mapping"
SOURCE_KPI_CONFIG = "kpi_config"
SOURCE_KEYWORD_SEARCH = "keyword_search"
SOURCE_UNKNOWN = "unknown"

SOURCE_TYPES = {
    SOURCE_JUGUANG,
    SOURCE_PGY,
    SOURCE_XIAOHONGXING_ORDER,
    SOURCE_NOTE_MAPPING,
    SOURCE_TASK_MAPPING,
    SOURCE_KPI_CONFIG,
    SOURCE_KEYWORD_SEARCH,
    SOURCE_UNKNOWN,
}
